@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.blakebr0.extendedcrafting.client.container.automationinterface;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;
